Repository devleo10/TechPulse, pull requests merged in 2025-03, with the labels that each got.

#7 Add a trending News Section
  .gitignore
  src/App.css
  src/App.js
  src/Context.js
  src/Pagination.js
  src/PopularNews.jsx
  src/Search.js
  src/reducer.js
Labels: enhancement, apertre2.0, easy, frontend

#20 Adding Navbar
  .gitignore
  package-lock.json
  src/App.css
  src/App.jsx
  src/Navbar.css
  src/Navbar.jsx
Labels: enhancement, apertre2.0, easy, frontend

#30 Add contribution guide to ReadeMe
  README.md
Labels: apertre2.0, doc

#31 Performance Optimization for TechPulse
  index.html
  package.json
  src/App.css
  src/App.jsx
  src/Context.jsx
  src/Pagination.jsx
  src/PopularNews.jsx
  src/Stories.jsx
  src/components/Loader.jsx
  src/components/styles/Loader.css
  src/index.jsx
  src/pages/Bookmarks.jsx
  src/pages/Home.jsx
  vite.config.js
Labels: enhancement, apertre2.0, hard, performance

#33 Feat/add 404 page
  src/App.jsx
  src/components/NotFound.jsx
  src/components/styles/notfound.css
Labels: apertre2.0, easy

#38 Feat/add reading mode
  src/App.jsx
  src/Context.jsx
  src/PopularNews.jsx
  src/Search.jsx
  src/Stories.jsx
  src/components/ReadingMode.jsx
  src/components/styles/ReadingMode.css
  src/reducer.js
Labels: apertre2.0, medium
